twitter:
  consumer_key: "IANgkT1nd56vRlM6Qqu3Oxn2C"
  consumer_secret: "VyfZzl9YAAdNqHj12PRk1oX8EZXWnA58RIxjG2E1NOzhrERkPb"
  access_token: "29650035-O1mGOswJj3XeEsveSc8QW3Lz6mmYGvWWbZmPeAgXq"
  access_token_secret: "k79NwcMe1qzLBOXbyFLwo4373lI0KLKSBzoshhK5V8IOr"
  timeout_ms: 60000
  
elasticsearch:
  host: "storyteller.eastus2.cloudapp.azure.com:9200"
  log: "error"
  index: "escape2016"

express:
  port: 3000

event:
  name: "DevConf 2017"
  start: 1470261600
  end: 1470348000
  organizers:
    - bbdsoftware
  speakers:
    - bbdsoftware
    - devconfza
    - mikegeyser
    - rorypreddy
    - rmaclean
    - williamBZA
  hashtags:
    - bbdsoftware
    - DevConf
    - DevConfZA
    - DevConf2017
    - DevConfZA2017    